import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class Main {
    public static void main(String[] args) {
        List<Voter> v = new ArrayList<>();
        v.add(new AntiSystem());
        v.add(new AntiSystem());
        v.add(new AntiSystem());
        v.add(new AntiSystem());
        v.add(new AntiSystem());
        v.add(new AntiSystem());
        v.add(new AntiSystem());
        v.add(new AntiSystem());
        v.add(new AntiSystem());
        v.add(new AntiSystem());
        v.add(new AntiSystem());
        v.add(new AntiSystem());
        v.add(new AntiSystem());
        v.add(new AntiSystem());
        v.add(new AntiSystem());
        v.add(new AntiSystem());
        v.add(new AntiSystem());
        v.add(new AntiSystem());
        v.add(new Party("PiS"));
        v.add(new Party("PiS"));
        v.add(new Party("PiS"));
        v.add(new Party("PiS"));
        v.add(new Party("PiS"));
        v.add(new Party("PiS"));
        v.add(new Party("PiS"));
        v.add(new Party("PiS"));
        v.add(new Party("PiS"));
        v.add(new Party("PiS"));
        v.add(new Party("PiS"));
        v.add(new Party("PiS"));
        v.add(new Party("PiS"));
        v.add(new Party("PiS"));
        v.add(new Party("PiS"));
        v.add(new Party("PiS"));
        v.add(new Party("PiS"));
        v.add(new Party("PiS"));
        v.add(new Party("PO"));
        v.add(new Party("PO"));
        v.add(new Party("PO"));
        v.add(new Party("PO"));
        v.add(new Party("PO"));
        v.add(new Party("PO"));
        v.add(new Party("PO"));
        v.add(new Party("PO"));
        v.add(new Party("PO"));
        v.add(new Party("PO"));
        v.add(new Party("PO"));
        v.add(new Party("PO"));
        v.add(new Party("PO"));
        v.add(new Party("PO"));
        v.add(new Party("PO"));
        v.add(new Party("PO"));
        v.add(new Party("PO"));
        v.add(new Party("SLD"));
        v.add(new Party("SLD"));
        v.add(new Party("PSL"));
        v.add(new Party("PSL"));
        v.add(new Party("SLD"));
        v.add(new Party("SLD"));
        v.add(new Party("PSL"));
        v.add(new Party("PSL"));
        v.add(new Feminist());
        v.add(new Feminist());
        v.add(new Feminist());
        v.add(new Feminist());
        v.add(new Feminist());
        v.add(new Bored());
        v.add(new Bored());
        v.add(new Bored());
        v.add(new Bored());
        v.add(new Bored());
        v.add(new Bored());
        v.add(new Bored());
        v.add(new Bored());
        v.add(new Bored());
        v.add(new Bored());
        v.add(new Bored());
        v.add(new Bored());
        v.add(new Bored());
        v.add(new Bored());
        v.add(new Bored());
        v.add(new Bored());
        v.add(new Bored());
        v.add(new Bored());
        v.add(new Bored());
        v.add(new Bored());
        v.add(new Bored());
        v.add(new Bored());
        v.add(new Bored());
        v.add(new Bored());
        v.add(new Bored());
        v.add(new Bored());
        v.add(new Bored());
        v.add(new Bored());
        v.add(new Bored());

        Election e = new Election(v);
        Map<Candidate, String> list = new HashMap<>();
        list.put(new Candidate("Andrzej", "Duda", false), "PiS");
        list.put(new Candidate("Bronisław", "Komorowski", false), "PO");
        list.put(new Candidate("Paweł", "Kukiz", false), null);
        list.put(new Candidate("Magdalena", "Ogórek", true), "SLD");
        list.put(new Candidate("Adam", "Jarubas", false), "PSL");
        list.put(new Candidate("Jan", "Tanajno", false), null);
        list.put(new Candidate("Grzegorz", "Braun", false), null);

        e.election(list);
        System.out.println(e.giveResults());
    }
}
